### ISSUE TITLE
Software problem

### ISSUE THREAD

**Issue by bgrattan3** [Whyzanet/WhyzaGC#4]
Anyone know how to contact the software author here?
Thanks

**Comment by Whyzanet** [comment]
Hi Bob

Whats the issue ?

**Comment by bgrattan3** [comment]
﻿
Hello,
I’ve had a MO GC running for about a year running Whyzanet software (3.5 I think) and it’s been stopping lately. I recompiled and uploaded. It goes through one cycle, sending data to radmon.org and then stops. I checked the MOGC and the serial port is putting out ok. Could possibly be a bad Esp32 although it takes other uploads (blink, wifi scanner) ok. I tried the latest Whyzanet software which loads on the esp32 but won’t connect to the MOGC.
I’m not a programmer so am somewhat lost here. Any help or suggestions would be welcome. I have ordered another esp32 just in case. Thanks in advance.
Bob
Ashland, VA
grattans.org/wx (where I display gc readings)

On Dec 30, 2023, at 14:17, Whyzanet ***@***.***> wrote:

﻿

Hi Bob

Whats the issue ?

**Comment by Whyzanet** [comment]
Hi Bob

Do you have a link to the MO GC ?

Can you post the serial output of the MO and/or WhyzaGC ?

Can you post the output of the diagnostics web page after the problem occurs  via http://whyzagc-esp.local

**Comment by Whyzanet** [comment]
Hi Bob

Sorry, its early in the morning here in AU.
The MO is of course the Mighty Ohm ;)

Send through the requested diagnostics if you can.
Cheers

**Comment by bgrattan3** [comment]
Thanks, will do. I’ll get things together. No direct link, just through radmon on the left side of my page.

On Dec 30, 2023, at 15:43, Whyzanet ***@***.***> wrote:

﻿

Hi Bob

Sorry, its early in the morning here in AU.
The MO is of course the Mighty Ohm ;)

Send through the requested diagnostics if you can.
Cheers

**Comment by bgrattan3** [comment]
Here is some info. Beginning of file shows the web page which seems to be fine but stops after a minute when the huzza reboots. The GC is still showing up on the LAN at 192.168.1.200 but no updates.

Following the web page is output from the serial monitor of IDE in debug mode. I had to do lots of cut/pasting because I didn't know how to capture the output. It shows running until it hits a snag and reboots.  There are some odd characters showing up so that may indicate some problem.

Much appreciated for the help. I can send more info if needed.

Cheers,
Bob
________________________________

**Comment by Whyzanet** [comment]
OK..so the issue is the reboots by the look of it ?

Check the basics like a stable power supply and associated hardware such as cables. 

Does it reboot when the radmon function is running, indicated by the purple LED flash and the subsequent green or red flash result ?

Another issue could be if you have recompiled against an updated library that no longer works as expected and causes a reboot, as such it would be useful to know what the unit is doing when it reboots...ie is it triggered by the radmon upload which occurs after 1 minute. I list the library versions I tested against in the main article which may help to track that sort of issue down.

If your libraries, hardware cabling and power supply setup is good, you would then need to eliminate a hardware issue with the Huzzah.

This log message could be hardware...

assert failed: xEventGroupClearBits event_groups.c:495 (xEventGroup)

Hopefully your additional Huzzah ESP32 unit is not far away as it would be a useful test considering the error message above to see if different hardware resolves the issue.

Hope this helps
Cheers

**Comment by Whyzanet** [comment]
I forgot to mention you could also try the lastest version 4.4.

There were some issues I fixed along the way, and while they are undocumented, it would be worth a go.

**Comment by bgrattan3** [comment]
Hi Whyzanet (sorry, I don’t know your name)

Cables and power are ok. The reboot occurs during the radmon upload. LED flashes colors but then the reboot and the system locks, but still shows up on my LAN.
I usually update my libraries when they are available so this could be an issue, however it was working fine but started locking and giving me the error that serial was not attached to the GC. After a restart, it would work for a few days.
I recompiled using updated libraries and it got  worse as it is now.
I tried the latest version which said the serial wasn’t attached and never ran at all.
Hopefully it’s a bad Huzzah chip. Maybe it will come next week.

Thanks for all the help. Best wishes for the new year—I guess it’s already there for you.
Cheers,
Bob


On Dec 30, 2023, at 17:47, Whyzanet ***@***.***> wrote:

﻿

OK..so the issue is the reboots by the look of it ?

Check the basics like a stable power supply and associated hardware such as cables.

Does it reboot when the radmon function is running, indicated by the purple LED flash and the subsequent green or red flash result ?

Another issue could be if you have recompiled against an updated library that no longer works as expected and causes a reboot, as such it would be useful to know what the unit is doing when it reboots...ie is it triggered by the radmon upload which occurs after 1 minute. I list the library versions I tested against in the main article which may help to track that sort of issue down.

If your libraries, hardware cabling and power supply setup is good, you would then need to eliminate a hardware issue with the Huzzah.

This log message could be hardware...

assert failed: xEventGroupClearBits event_groups.c:495 (xEventGroup)

Hopefully your additional Huzzah ESP32 unit is not far away as it would be a useful test considering the error message above to see if different hardware resolves the issue.

Hope this helps
Cheers

**Comment by bgrattan3** [comment]
Hello,

I have my new Adafruit ESP32 V2 Huzzah with a new set of problems. I have run a compile on your version 4.4 but can't get it to load (see attached error file). The chip arrived with the "scan" program loaded and it runs scanning the available wifi. However I don't know how to stop the scan program to load WhyzaGC.
As a non-programmer, this is probably a simple problem but I can't get past it.
How can I put it in download mode?  Thanks.
Bob
________________________________

**Comment by Whyzanet** [comment]
Hi Bill.

I checked your logs above for the last messages, but I think they are truncated if you can check ? 
Are you able to compile and load up any examples such as blink ?
The programming mode is accessed via a reboot of the ESP32 while holding a GPIO pin low, which is done automagically by 
 the IDE and the USB cable you are using.
This document has details at the top of what should occur to enter bootmode for programming mode so you are aware. 
https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection/aafa99589a9a2e4a147c91a9594c1f53562c2061

**Comment by bgrattan3** [comment]
It seems that scan came installed and runs when I connect to a usb. I have tried to load blink with IDE but always get the same error that it's not in download mode. I thought that IDE would auto go into boot mode and then reset when upload is finished. Doesn't seem to do that. Which pin do I need to ground to get download mode? Which is GPIO0 on the V2? Thanks
Bob
________________________________

**Comment by Whyzanet** [comment]
Yes you are correct, the IDE should do all this for you.
At the end of the main article I have the Huzzah V2 pinouts...it appears GPIO is not available on the Huzzah, as there is no need if the IDE can do it.
I suggest you check your serial ports and settings and USB cable, and a different ESP32 to narrow down the issue to get blink loaded. 

Are you using the Arduino IDE ?

**Comment by bgrattan3** [comment]
I have the latest IDE on win10 and ubuntu. I was able to upload blink and scan on my old esp32 v2 but now it gives me the same message about not being in download mode. Not sure what to do here…

On Jan 7, 2024, at 17:11, Whyzanet ***@***.***> wrote:

﻿

Yes you are correct, the IDE should do all this for you.
At the end of the main article I have the Huzzah V2 pinouts...it appears GPIO is not available on the Huzzah, as there is no need if the IDE can do it.
I suggest you check your serial ports and settings and USB cable, and a different ESP32 to narrow down the issue to get blink loaded.

Are you using the Arduino IDE ?

**Comment by Whyzanet** [comment]
Hey Bob ( got it right this time !)
It sounds like a low level issue such as serial port related problems if download mode can not be enabled.
Check your serial speed ( 115200 ) , USB port and usb c cable ( different port and different cable ).

**Comment by bgrattan3** [comment]
Hello,
OK, I have managed to load WhyzaGC 4.4 and it seems to have loaded ok.
I'm now getting the message that the serial isn't connected to pin #27. I've moved things around, changed leads, etc. but still get the error message.
It seems to register one output from the MO after a minute or so but that's all. No serial error message is still coming up.
Here is a file of outputs. Maybe they will tell something of the problem.

Is it possible the serial output on the MO isn't working correctly? What do I need to check for this possible problem?
Thanks and sorry to keep bothering you.
Cheers,
Bob
________________________________

**Comment by Whyzanet** [comment]
Does v3.5 do the same ?

**Comment by Whyzanet** [comment]
OK

Can you send me the web diagnostics taken after the problem occurs via http://whyzagc-esp.local ?

**Comment by bgrattan3** [comment]
Sorry, not sure what you mean by web diagnostics. Is this just what appears on the screen when I access by the web? The two shots in the file I sent show
1.  IDE serial monitor output
2.  Web data screen
Just let me know what else I need to send.

Earlier I tested the MO with an FTDI interface on the serial pins and it was putting out ok. However, since the FTDI gismo was powered then it might have compensated for a weak signal coming from the MO (just an unsophisticated guess).
Many thanks for your continued help.
Bob

On Jan 9, 2024, at 14:45, Whyzanet ***@***.***> wrote:

﻿

OK

Can you send me the web diagnostics taken after the problem occurs via http://whyzagc-esp.local<http://secure-web.cisco.com/1DgNqbVWQOlj2QopnASbRJ-LzkCzA0rTihmUpG8eSllUzdLTlB5R3QDc9p2G3FL5R1WHTBhtwu6qdLaf1A05tZkwQW6sKs3DGArkbqx7JA26G5MsWR1kRdXPqPoepvmWjNqpTq-aKolt4vVpAKtLmmwFMZRPUCZyN4z8sBrz_qe8ea_8u0VoHAJNJsBySVIrr_wJlGqXPaax_4Tunt_gFir0UKbehbLWxN7jqWQ2wIEDWG3GiRCQu4rzTGyyQam64dmPVPcIwoKJCklhYAft8ky1ehNvPzGOVjh5oiQDUCoKYhrfHlVEocxTRUUL4T3i0/http%3A%2F%2Fwhyzagc-esp.local> ?

**Comment by Whyzanet** [comment]
I am unable to see the diagnostics you sent. Are you able to paste them into a response on Github ?

**Comment by bgrattan3** [comment]
Hope this is better

Output on IDE serial monitor
================================================================
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1256
load:0x40078000,len:13832
load:0x40080400,len:4
load:0x40080404,len:3048
entry 0x40080590
E (390) adc_share_hw_��� adc_lock_release(150): adc1 lock release without acquiring
[   228][I][esp32-hal-psram.c:92] psramInit(): PSRAM enabled
[   272][I][esp32-hal-i2c.c:108] i2cInit(): Initialising I2C Master: sda=22 scl=20 freq=100000

 ________  __           ____                         __
|  |  |  ||  |_ .--.--.|_  / .-----.   .-----.-----.|  |_
|  |  |  ||    ||  |  | / /_ | -   | _ |     |  -__||   _|
|________||__|_||__   ||____||___|_||_||__|__|_____||____|
                   |__|        
WhyzaGC v4.4
Released 26/8/2023
grattanrt
.
WiFi status
IPv4: 192.168.1.200
[  4421][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
[  7434][I][WiFiClient.cpp:260] connect(): select returned due to timeout 3000 ms for fd 50
Stats available:
http://WhyzaGC.local
Software upload:
http://WhyzaGC.local/upload
Opened serial server on telnet://192.168.1.200:23
Opened serial web server on http://192.168.1.200:81
[  7472][E][ESPmDNS.cpp:149] addService(): Failed adding service http.tcp.

[  7494][I][ArduinoOTA.cpp:141] begin(): OTA server at: WhyzaGC-ESP32.local:3232
CPS, 0, CPM, 17, uSv/hr, 0.09, SLOW
=====================================================================================

Output on 192.168.1.200:80

=====================================================================================

WhyzaGC v4.4
Released 26/8/2023
Hardware: Feather Huzzah ESP32 v2

 ________  __           ____                         __
|  |  |  ||  |_ .--.--.|_  / .-----.   .-----.-----.|  |_
|  |  |  ||    ||  |  | / /_ | -   | _ |     |  -__||   _|
|________||__|_||__   ||____||___|_||_||__|__|_____||____|
                   |__|        

10:06:26
Uptime: 0 days, 0 hours, 6 minutes, 26 seconds

Geiger Connected: false 

Rolling Average CPM: 17
Rolling 1 hour Average CPM: 17

uSieverts/Hour: 0.09
mSieverts/Year: 0.79

Last Radmon Update(secs): 386
Radmon HTTP Get status code: 0
Radmon HTTP Get response body: 
Last Upload Delay(ms): 0
Rolling 1 hour Average Upload Delay(ms): 0
Rolling 1 day Average Upload Delay(ms): 0
Last Radmon Update CPM: 0

Current Data:CPS, 0, CPM, 17, uSv/hr, 0.09, SLOW

Debug:
Scale: 2.00 recenthi: 2 xplot: 17

**Comment by bgrattan3** [comment]
Output on IDE serial monitor
================================================================
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1256
load:0x40078000,len:13832
load:0x40080400,len:4
load:0x40080404,len:3048
entry 0x40080590
E (390) adc_share_hw_��� adc_lock_release(150): adc1 lock release without acquiring
[   228][I][esp32-hal-psram.c:92] psramInit(): PSRAM enabled
[   272][I][esp32-hal-i2c.c:108] i2cInit(): Initialising I2C Master: sda=22 scl=20 freq=100000

 ________  __           ____                         __
|  |  |  ||  |_ .--.--.|_  / .-----.   .-----.-----.|  |_
|  |  |  ||    ||  |  | / /_ | -   | _ |     |  -__||   _|
|________||__|_||__   ||____||___|_||_||__|__|_____||____|
                   |__|        
WhyzaGC v4.4
Released 26/8/2023
grattanrt
.
WiFi status
IPv4: 192.168.1.200
[  4421][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
[  7434][I][WiFiClient.cpp:260] connect(): select returned due to timeout 3000 ms for fd 50
Stats available:
http://WhyzaGC.local
Software upload:
http://WhyzaGC.local/upload
Opened serial server on telnet://192.168.1.200:23
Opened serial web server on http://192.168.1.200:81
[  7472][E][ESPmDNS.cpp:149] addService(): Failed adding service http.tcp.

[  7494][I][ArduinoOTA.cpp:141] begin(): OTA server at: WhyzaGC-ESP32.local:3232
CPS, 0, CPM, 17, uSv/hr, 0.09, SLOW
=====================================================================================

Output on 192.168.1.200:80

=====================================================================================

WhyzaGC v4.4
Released 26/8/2023
Hardware: Feather Huzzah ESP32 v2

 ________  __           ____                         __
|  |  |  ||  |_ .--.--.|_  / .-----.   .-----.-----.|  |_
|  |  |  ||    ||  |  | / /_ | -   | _ |     |  -__||   _|
|________||__|_||__   ||____||___|_||_||__|__|_____||____|
                   |__|        

10:06:26
Uptime: 0 days, 0 hours, 6 minutes, 26 seconds

Geiger Connected: false 

Rolling Average CPM: 17
Rolling 1 hour Average CPM: 17

uSieverts/Hour: 0.09
mSieverts/Year: 0.79

Last Radmon Update(secs): 386
Radmon HTTP Get status code: 0
Radmon HTTP Get response body: 
Last Upload Delay(ms): 0
Rolling 1 hour Average Upload Delay(ms): 0
Rolling 1 day Average Upload Delay(ms): 0
Last Radmon Update CPM: 0

Current Data:CPS, 0, CPM, 17, uSv/hr, 0.09, SLOW

Debug:
Scale: 2.00 recenthi: 2 xplot: 17

**Comment by bgrattan3** [comment]
Sorry if this didn't come through. Not sure how to do this

**Comment by bgrattan3** [comment]
I pasted on GitHub but probably didn't do it correctly. Let me know if you still can't see it.
________________________________

**Comment by Whyzanet** [comment]
Thaks.
So it does see some serial output as per this in the Web diagnostics
Current Data:CPS, 0, CPM, 17, uSv/hr, 0.09, SLOW
But it sees issues with the serial connection at the time the diagnostics were generated
Geiger Connected: false

Sorry to be a pain, but can you try 2 things and send me the same diagnostics ?

1. try the 3.5 firmware.
2. Specify a functioning remote syslog host if you have not already in the top of the sketch. I suspect there maybe a bug in this area. 

To enable remote syslog on Ubuntu you need to have these lines active in /etc/rsyslogd.conf

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

**Comment by bgrattan3** [comment]
Thanks, I'll try but have to cook dinner. I'll reload 3.5 and do the syslog thing tomorrow.
May be afternoon (EST) before I can try.
Much appreciated for your time and patience.
Cheers,
Bob
________________________________

**Comment by Whyzanet** [comment]
You only really need the first two lines for /etc/rsyslogd.conf as the sketch library uses UDP.

module(load="imudp")
input(type="imudp" port="514")

You will need to restart rsyslogd after the change with 

sudo systemctl restart rsyslogd

**Comment by bgrattan3** [comment]
I am attaching two files: syslog showing both V 4.4 and then 3.5 and serial monitor output for both sessions.

The 4.4 gave one reading and stopped. For some odd reason the 3.5 started and was working, at lease for a while. Before, when I was using 3.5, it would run for some hours and then stop, then run for a few hours after reset and stop again.
Not sue what is going on here. Thanks.
Bob
[WhyzaGC_serial monitor.txt](https://github.com/Whyzanet/WhyzaGC/files/13893584/WhyzaGC_serial.monitor.txt)
[WHYZAGC_syslog.txt](https://github.com/Whyzanet/WhyzaGC/files/13893587/WHYZAGC_syslog.txt)

**Comment by Whyzanet** [comment]
They both have this startup error in the serial output

[  4580][E][ESPmDNS.cpp:149] addService(): Failed adding service http.tcp.

which implies there is a networking issue. 

ESP8266mDNS(1.2) (for ESP8266): [https://github.com/LaborEtArs/ESP8266mDNS]

Here are my syslogs ( ignore version 4.5...its the same as 4.4 )

Jan 11 06:38:36 WhyzaGC-ESP32 wifion: ﻿WhyzaGC v4.5                                                                     
Jan 11 06:38:36 WhyzaGC-ESP32 wifion: ﻿Released: 23/10/2023                                                             
Jan 11 06:38:36 WhyzaGC-ESP32 wifion: ﻿System Status: Online                                                            
Jan 11 06:38:36 WhyzaGC-ESP32 wifion: ﻿Resolved NTP server hostname successfully                                        
Jan 11 06:38:36 WhyzaGC-ESP32 wifion: ﻿ntp.lan > 192.168.0.3                                                                                   
Jan 11 06:38:39 WhyzaGC-ESP32 wifion: ﻿Assigned WiFi IP Address: 192.168.0.100                                          
Jan 11 06:38:39 WhyzaGC-ESP32 setup: ﻿Initial setup successful                                                          
Jan 11 06:38:39 WhyzaGC-ESP32 setup: ﻿Resolved MQTT broker hostname successfully                                        
Jan 11 06:38:39 WhyzaGC-ESP32 setup: ﻿mqtt.lan > 192.168.0.3      


Do you have a valid NTP server configured ?

**Comment by Whyzanet** [comment]
Hi Bob

Looking closer I can see you don't have a NTP server configured by the look of it.
That said, a lack of NTP server should not cause this issue.

I will try to get some time to have a closer look at my serial output and see if I am getting the same ESPmDNS error which can hopefully be igmored.

**Comment by Whyzanet** [comment]
Another useful diagnostic would be what the regular blue flashing LED is doing.

It flashes for every EOL detected in the MightyOhm serial data output.
As it is having trouble detecting the MO output, I guess this would be affected. 

Can you confirm the blue led stop flashing when the issue occurs ?

**Comment by bgrattan3** [comment]
Here's the latest:
I was out for a couple of hours and the MO with WhyzaGC 3.3 was still working correctly. Blue LED working correctly.

I recompiled 4.4 and added "bool NTP_Use_Hostname = true;" [was false]
It loaded ok but did not run after the first MOGC reading. Blue LED not flashing. No other LEDs on.
syslog:
Jan 10 16:51:10 WhyzaGC-ESP32 wifion: WhyzaGC v4.4
Jan 10 16:51:10 WhyzaGC-ESP32 wifion: Released 26/8/2023
Jan 10 16:51:10 WhyzaGC-ESP32 wifion: System Status: Online
Jan 10 16:51:10 WhyzaGC-ESP32 wifion: Resolved NTP server hostname successfully
Jan 10 16:51:10 WhyzaGC-ESP32 wifion: pool.ntp.org > 15.204.87.223
Jan 10 16:51:13 WhyzaGC-ESP32 wifion: Assigned WiFi IP Address: 192.168.1.200
Jan 10 16:51:13 WhyzaGC-ESP32 setup: Initial setup successful
Jan 10 16:51:13 WhyzaGC-ESP32 setup: Using configured MQTT broker IP address:
Jan 10 16:51:13 WhyzaGC-ESP32 setup: 192.168.1.10
Jan 10 16:51:21 WhyzaGC-ESP32 serialmon: Geiger not connected! - Check serial port

**Comment by bgrattan3** [comment]
Telnet (23) and web (81) were working correctly on 3.3

on 4.4 no telnet and web (80) showed the first line of data from MO but nothing more.

**Comment by Whyzanet** [comment]
To be honest Bob, I am not sure what else we can check without me making a sketch that has some further debugging enabled.

Can you verify the MO is stable over a serial connection to a PC ?
Can you verify if 3.5 firmware is stable ?

There is really not much to go wrong with the serial connection other than the 1 wire connection. Check it for sanity.

**Comment by bgrattan3** [comment]
I’ll hook up the serial output with an FTDI again to see if it’s stable for a while. 3.3 was working again yesterday but 4.4 has never worked because of the serial problem. I am interested in 4.4 because of the MQTT as I have other sensors connected to my weather station. I’ll keep digging and keep you posred. Thanks.

**Comment by bgrattan3** [comment]
Sorry, been out with medical problems for several days. One last idea.
If I send you my version of WhyzaGC_4_4_ESP32.ino (IP addresses, wifi passwords, etc.) could you compile on your system and send me the binary? No idea how to load a binary with IDE but there must be a way. It's possible some of my IDE libraries are not the ones you are using so this would tell me that my compiles are the problem. If this is asking too much then not to worry, I'll figure out something else. I am not a programmer so my debugging is very limited. Thanks for the help.
Cheers,
Bob

**Comment by Whyzanet** [comment]
yeah I can do that.

You can load the binary up directly to the unit via the http upgrade 

http://whyzagc-esp.local/upload

**Comment by bgrattan3** [comment]
Thanks. I have zipped up the build folder in case that will show you anything. I will send build and .ino.
Can you suggest a secure way to send as it has passwords and IDs showing? I don't belong to any clouds so maybe your personal email would be best if you want to let me have it. I can't imagine anyone would be interested in my GC enough to hack it so I can send it through your GitHub if needed.

Before compiling, could you have a look at the MQTT section as I'm not certain I have all of that correct. I'm sending data to an Ubuntu server at 192.168.1.119 on my local network which is already getting MQTT data from a couple of sources.

Much appreciated for the extra help. I just want to try everything possible before I throw the whole thing out the window...
Cheers,
Bob
***@***.***

________________________________

**Comment by Whyzanet** [comment]
Can you post a email address I can contact you on  ?

**Comment by bgrattan3** [comment]
I posted it but it looks like it was commented out.
Look at my site http://grattans.org/wx.

On Jan 18, 2024, at 18:33, Whyzanet ***@***.***> wrote:

﻿

Can you post a email address I can contact you on ?

**Comment by bgrattan3** [comment]
Maybe bgrattanatumwdotedu will work

On Jan 18, 2024, at 18:33, Whyzanet ***@***.***> wrote:

﻿

Can you post a email address I can contact you on ?

**Comment by Whyzanet** [comment]
I cant see an email in your page....I even checked the src
I check that last week thinking it might be there

**Comment by Whyzanet** [comment]
Issue resolved in version 4.7 software
NTP client was causing issues
